### ISSUE TITLE
1.0.0.5 vipm package? 

### ISSUE THREAD

**Issue by erotenberg1** [LabVIEW-Open-Source/Connection#1]
I would very much like to try this out but I need 1.0.0.5 in order to use it with the Labview-Open-Source/oauth2 client package.  Is there a package for this forthcoming? All I can find online is 1.0.0.4.  

Edit: I mean, a package for the VIPM installer.

thank you very much.

**Comment by francois-normandin** [comment]
Hi @erotenberg1 ,

Indeed, I made an error when building the package with a local dependency instead of the public one. 
There is no difference between 1.0.0.4 and 1.0.0.5. 
You can install build4 and it will work. Of course, there will be a missing dependency mention in VIPM as a result... 
I'll fix this and publish an update soon.

best

**Comment by erotenberg1** [comment]
thanks so much for the very fast reply.

**Comment by francois-normandin** [comment]
I should not be thanked for neglecting to fix something that I noticed a long time ago. :-(
I've been very lazy... ;-)

**Comment by francois-normandin** [comment]
@erotenberg1 
Package 1.0.0.5 is released.

You can download here right now:
https://github.com/LabVIEW-Open-Source/Connection/releases/tag/1.0.0

Or it will be on VIPM Community shortly... getting through the publication process.

**Comment by erotenberg1** [comment]
thank you again for your help.

Eli
